namespace Ezrie.AdministrationService.EntityFrameworkCore;

public abstract class AdministrationServiceEntityFrameworkCoreTestBase : AdministrationServiceTestBase<AdministrationServiceEntityFrameworkCoreTestModule>
{

}
