version: '3.7'

volumes:
  postgres_data:
  pgadmin_data:
  seq_data:

services:

  db:
    container_name: postgres
    image: postgres:latest
    hostname: db.ezrie.ca
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "myPassword"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    hostname: pgadmin.ezrie.ca
    environment:
      PGADMIN_DEFAULT_EMAIL: root@ezrie.ca
      PGADMIN_DEFAULT_PASSWORD: nji(0okM
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    hostname: rabbitmq.ezrie.ca
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    container_name: redis
    image: redis:alpine
    hostname: redis.ezrie.ca
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    ports:
      - "6379:6379"

  seq:
    container_name: seq
    image: datalust/seq:latest
    hostname: seq.ezrie.ca
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
    ports:
      - "5341:80"
