version: '3.7'

services:

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    ports:
      - "6379:6379"

  db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "myPassword"

  pgadmin:
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-root@ezrie.ca}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-1q2w3E*}

  seq:
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
