version: '3.4'

services:
  ezrie.accountmanagement.admin:
    image: ${DOCKER_REGISTRY-}ezrieaccountmanagementadmin
    build:
      context: .
      dockerfile: ../apps/Ezrie.AccountManagement/src/Ezrie.AccountManagement.Admin/Dockerfile

  ezrie.accountmanagement.sts:
    image: ${DOCKER_REGISTRY-}ezrieaccountmanagementsts
    build:
      context: .
      dockerfile: ../apps/Ezrie.AccountManagement/src/Ezrie.AccountManagement.STS/Dockerfile

  ezrie.gateway.public:
    image: ${DOCKER_REGISTRY-}ezriegatewaypublic
    build:
      context: .
      dockerfile: ../gateways/Ezrie.Gateway.Public/Dockerfile

  ezrie.administrationservice.httpapi.host:
    image: ${DOCKER_REGISTRY-}ezrieadministrationservicehttpapihost
    build:
      context: .
      dockerfile: ../services/Ezrie.AdministrationService/host/Ezrie.AdministrationService.HttpApi.Host/Dockerfile


  ezrie.identityservice.httpapi.host:
    image: ${DOCKER_REGISTRY-}ezrieidentityservicehttpapihost
    build:
      context: .
      dockerfile: ../services/Ezrie.IdentityService/host/Ezrie.IdentityService.HttpApi.Host/Dockerfile


  ezrie.tenantservice.httpapi.host:
    image: ${DOCKER_REGISTRY-}ezrietenantservicehttpapihost
    build:
      context: .
      dockerfile: ../services/Ezrie.TenantService/host/Ezrie.TenantService.HttpApi.Host/Dockerfile
